// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct represents the main application
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * BrowseFolder opens a folder selection dialog using Windows API
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function BrowseFolder(title) {
    return $Call.ByID(3225197899, title);
}

/**
 * GetLastUsedPath returns the last used path for a given key
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetLastUsedPath(key) {
    return $Call.ByID(3617481933, key);
}

/**
 * GetPreference returns a preference value
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetPreference(key) {
    return $Call.ByID(2867728738, key);
}

/**
 * SetLastUsedPath sets the last used path for a given key
 * @param {string} key
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetLastUsedPath(key, path) {
    return $Call.ByID(2107975385, key, path);
}

/**
 * SetPreference sets a preference value
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetPreference(key, value) {
    return $Call.ByID(3639510670, key, value);
}

/**
 * WailsInit is called when the app starts
 * @returns {$CancellablePromise<void>}
 */
export function WailsInit() {
    return $Call.ByID(2090703335);
}

/**
 * WailsShutdown is called when the app is shutting down
 * @returns {$CancellablePromise<void>}
 */
export function WailsShutdown() {
    return $Call.ByID(3922507855);
}
