// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RetocService handles Retoc operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelOperation cancels a running retoc operation by its ID
 * @param {string} operationID
 * @returns {$CancellablePromise<void>}
 */
export function CancelOperation(operationID) {
    return $Call.ByID(2756521279, operationID);
}

/**
 * CancelOperationByCommand cancels the currently running operation of a specific command type
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function CancelOperationByCommand(command) {
    return $Call.ByID(1836650763, command);
}

/**
 * RunRetoc executes a Retoc operation
 * @param {$models.RetocOperation} operation
 * @returns {$CancellablePromise<$models.RetocResult>}
 */
export function RunRetoc(operation) {
    return $Call.ByID(1206917166, operation).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RetocResult.createFrom;
