// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UAssetService handles UAsset operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CountJSONFiles counts .json files in a directory
 * @param {string} folderPath
 * @returns {$CancellablePromise<number>}
 */
export function CountJSONFiles(folderPath) {
    return $Call.ByID(2521123928, folderPath);
}

/**
 * CountUAssetFiles counts .uasset and .uexp files in a directory
 * @param {string} folderPath
 * @returns {$CancellablePromise<[number, number]>}
 */
export function CountUAssetFiles(folderPath) {
    return $Call.ByID(3817039997, folderPath);
}

/**
 * ExportUAssets exports .uasset/.uexp files to JSON
 * @param {string} folderPath
 * @returns {$CancellablePromise<$models.UAssetResult>}
 */
export function ExportUAssets(folderPath) {
    return $Call.ByID(4083550300, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ImportUAssets imports JSON files back to .uasset/.uexp
 * @param {string} folderPath
 * @returns {$CancellablePromise<$models.UAssetResult>}
 */
export function ImportUAssets(folderPath) {
    return $Call.ByID(2570316673, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UAssetResult.createFrom;
